// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInteger-1]
	_ = x[TypeString-2]
	_ = x[TypeBoolean-3]
	_ = x[TypeNull-4]
	_ = x[TypeReturn-5]
	_ = x[TypeError-6]
	_ = x[TypeFunction-7]
	_ = x[TypeBuiltin-8]
	_ = x[TypeArray-9]
	_ = x[TypeHash-10]
}

const _Type_name = "IntegerStringBooleanNullReturnErrorFunctionBuiltinArrayHash"

var _Type_index = [...]uint8{0, 7, 13, 20, 24, 30, 35, 43, 50, 55, 59}

func (i Type) String() string {
	i -= 1
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
