// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILLEGAL-0]
	_ = x[EOF-1]
	_ = x[IDENT-2]
	_ = x[INT-3]
	_ = x[ASSIGN-4]
	_ = x[PLUS-5]
	_ = x[COMMA-6]
	_ = x[SEMICOLON-7]
	_ = x[LPAREN-8]
	_ = x[RPAREN-9]
	_ = x[LBRACE-10]
	_ = x[RBRACE-11]
	_ = x[FUNCTION-12]
	_ = x[LET-13]
}

const _Type_name = "ILLEGALEOFIDENTINT=+,;(){}fnlet"

var _Type_index = [...]uint8{0, 7, 10, 15, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 31}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
